development:
  sessions:
    default:
      uri: <%= ENV['MONGO_URL'] %>
test:
  sessions:
    default:
      uri: <%= ENV['MONGO_URL'] %>

production:
  sessions:
    default:
      uri: <%= ENV['MONGO_URL'] %>
